# Generated by Django 5.2.8 on 2025-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUMMARY', 'Summary'), ('REPORT', 'Report'), ('TRANSLATION', 'Translation'), ('CUSTOM', 'Custom')], default='SUMMARY', max_length=20)),
                ('user_prompt', models.TextField(blank=True, help_text='Optional user instructions', null=True)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt used for generation', null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
