# Generated by Django 5.2.8 on 2025-11-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='transcription_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='transcription.transcriptionjob'),
        ),
    ]
